# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTableView, QWidget)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(1080, 760)
        mainWindow.setMinimumSize(QSize(1080, 760))
        mainWindow.setMaximumSize(QSize(1080, 976))
        self.preference = QAction(mainWindow)
        self.preference.setObjectName(u"preference")
        self.help = QAction(mainWindow)
        self.help.setObjectName(u"help")
        self.about = QAction(mainWindow)
        self.about.setObjectName(u"about")
        self.feedback = QAction(mainWindow)
        self.feedback.setObjectName(u"feedback")
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1081, 721))
        self.tabWidget.setMinimumSize(QSize(1081, 721))
        self.tabWidget.setMaximumSize(QSize(1081, 721))
        self.manualSelector = QWidget()
        self.manualSelector.setObjectName(u"manualSelector")
        self.typeComboBox = QComboBox(self.manualSelector)
        self.typeComboBox.setObjectName(u"typeComboBox")
        self.typeComboBox.setGeometry(QRect(340, 20, 141, 22))
        self.label = QLabel(self.manualSelector)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(270, 20, 71, 21))
        self.refreshBtn = QPushButton(self.manualSelector)
        self.refreshBtn.setObjectName(u"refreshBtn")
        self.refreshBtn.setGeometry(QRect(510, 13, 81, 31))
        self.searchEdit = QLineEdit(self.manualSelector)
        self.searchEdit.setObjectName(u"searchEdit")
        self.searchEdit.setGeometry(QRect(800, 10, 251, 31))
        self.label_3 = QLabel(self.manualSelector)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 50, 71, 21))
        self.label_4 = QLabel(self.manualSelector)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 430, 71, 21))
        self.chooseClassBtn = QPushButton(self.manualSelector)
        self.chooseClassBtn.setObjectName(u"chooseClassBtn")
        self.chooseClassBtn.setGeometry(QRect(440, 653, 91, 31))
        self.addAutoBtn = QPushButton(self.manualSelector)
        self.addAutoBtn.setObjectName(u"addAutoBtn")
        self.addAutoBtn.setGeometry(QRect(580, 653, 91, 31))
        self.epochComboBox = QComboBox(self.manualSelector)
        self.epochComboBox.setObjectName(u"epochComboBox")
        self.epochComboBox.setGeometry(QRect(100, 20, 141, 22))
        self.label_12 = QLabel(self.manualSelector)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 20, 71, 21))
        self.courseTableView = QTableView(self.manualSelector)
        self.courseTableView.setObjectName(u"courseTableView")
        self.courseTableView.setGeometry(QRect(30, 80, 1021, 341))
        self.courseTableView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.courseTableView.setAlternatingRowColors(True)
        self.courseTableView.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.courseTableView.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.courseTableView.setSortingEnabled(True)
        self.courseTableView.setWordWrap(False)
        self.courseTableView.horizontalHeader().setMinimumSectionSize(0)
        self.courseTableView.horizontalHeader().setProperty(u"showSortIndicator", True)
        self.courseTableView.horizontalHeader().setStretchLastSection(True)
        self.courseTableView.verticalHeader().setMinimumSectionSize(0)
        self.courseTableView.verticalHeader().setDefaultSectionSize(20)
        self.classTableView = QTableView(self.manualSelector)
        self.classTableView.setObjectName(u"classTableView")
        self.classTableView.setGeometry(QRect(30, 460, 1021, 181))
        self.classTableView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.classTableView.setAlternatingRowColors(True)
        self.classTableView.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.classTableView.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.classTableView.setWordWrap(False)
        self.classTableView.horizontalHeader().setMinimumSectionSize(0)
        self.classTableView.horizontalHeader().setStretchLastSection(True)
        self.classTableView.verticalHeader().setVisible(True)
        self.classTableView.verticalHeader().setMinimumSectionSize(0)
        self.classTableView.verticalHeader().setDefaultSectionSize(20)
        self.tabWidget.addTab(self.manualSelector, "")
        self.autoSelector = QWidget()
        self.autoSelector.setObjectName(u"autoSelector")
        self.label_6 = QLabel(self.autoSelector)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 20, 111, 21))
        self.delAutoBtn = QPushButton(self.autoSelector)
        self.delAutoBtn.setObjectName(u"delAutoBtn")
        self.delAutoBtn.setGeometry(QRect(930, 130, 121, 41))
        self.switchAutoBtn = QPushButton(self.autoSelector)
        self.switchAutoBtn.setObjectName(u"switchAutoBtn")
        self.switchAutoBtn.setGeometry(QRect(930, 217, 121, 41))
        self.saveAutoBtn = QPushButton(self.autoSelector)
        self.saveAutoBtn.setObjectName(u"saveAutoBtn")
        self.saveAutoBtn.setGeometry(QRect(930, 307, 121, 41))
        self.clearAutoBtn = QPushButton(self.autoSelector)
        self.clearAutoBtn.setObjectName(u"clearAutoBtn")
        self.clearAutoBtn.setGeometry(QRect(930, 397, 121, 41))
        self.loadAutoBtn = QPushButton(self.autoSelector)
        self.loadAutoBtn.setObjectName(u"loadAutoBtn")
        self.loadAutoBtn.setGeometry(QRect(930, 487, 121, 41))
        self.autoCourseTableView = QTableView(self.autoSelector)
        self.autoCourseTableView.setObjectName(u"autoCourseTableView")
        self.autoCourseTableView.setGeometry(QRect(30, 50, 871, 611))
        self.autoCourseTableView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.autoCourseTableView.setAlternatingRowColors(True)
        self.autoCourseTableView.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.autoCourseTableView.setWordWrap(False)
        self.autoCourseTableView.horizontalHeader().setMinimumSectionSize(0)
        self.autoCourseTableView.horizontalHeader().setStretchLastSection(True)
        self.autoCourseTableView.verticalHeader().setVisible(True)
        self.autoCourseTableView.verticalHeader().setMinimumSectionSize(0)
        self.autoCourseTableView.verticalHeader().setDefaultSectionSize(20)
        self.tabWidget.addTab(self.autoSelector, "")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 730, 71, 21))
        self.cmdOutput = QPlainTextEdit(self.centralwidget)
        self.cmdOutput.setObjectName(u"cmdOutput")
        self.cmdOutput.setGeometry(QRect(30, 760, 1021, 151))
        self.cmdOutput.setReadOnly(True)
        self.cmdOutput.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByKeyboard|Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextBrowserInteraction|Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1080, 33))
        font = QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tabWidget, self.typeComboBox)
        QWidget.setTabOrder(self.typeComboBox, self.refreshBtn)
        QWidget.setTabOrder(self.refreshBtn, self.cmdOutput)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.preference)
        self.menu_2.addAction(self.help)
        self.menu_2.addAction(self.about)
        self.menu_2.addAction(self.feedback)

        self.retranslateUi(mainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"\u9009\u8bfe\u52a9\u624b", None))
        self.preference.setText(QCoreApplication.translate("mainWindow", u"\u9996\u9009\u9879", None))
        self.help.setText(QCoreApplication.translate("mainWindow", u"\u4f7f\u7528\u5e2e\u52a9", None))
        self.about.setText(QCoreApplication.translate("mainWindow", u"\u5173\u4e8e\u8f6f\u4ef6", None))
        self.feedback.setText(QCoreApplication.translate("mainWindow", u"\u95ee\u9898\u53cd\u9988", None))
        self.label.setText(QCoreApplication.translate("mainWindow", u"\u8bfe\u7a0b\u7c7b\u578b\uff1a", None))
        self.refreshBtn.setText(QCoreApplication.translate("mainWindow", u"\u5237\u65b0", None))
        self.searchEdit.setPlaceholderText(QCoreApplication.translate("mainWindow", u"\u952e\u5165\u4ee5\u641c\u7d22", None))
        self.label_3.setText(QCoreApplication.translate("mainWindow", u"\u8bfe\u7a0b\u5217\u8868\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("mainWindow", u"\u53ef\u9009\u8bb2\u53f0\uff1a", None))
        self.chooseClassBtn.setText(QCoreApplication.translate("mainWindow", u"\u9009\u62e9\u8bb2\u53f0", None))
        self.addAutoBtn.setText(QCoreApplication.translate("mainWindow", u"\u52a0\u5165\u62a2\u8bfe", None))
        self.label_12.setText(QCoreApplication.translate("mainWindow", u"\u9009\u8bfe\u8f6e\u6b21\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manualSelector), QCoreApplication.translate("mainWindow", u"\u9009\u8bfe\u4e2d\u5fc3", None))
        self.label_6.setText(QCoreApplication.translate("mainWindow", u"\u5faa\u73af\u62a2\u8bfe\u8bfe\u7a0b\u5217\u8868\uff1a", None))
        self.delAutoBtn.setText(QCoreApplication.translate("mainWindow", u"\u5220\u9664\u9009\u4e2d\u7684\u8bfe\u7a0b", None))
        self.switchAutoBtn.setText(QCoreApplication.translate("mainWindow", u"\u5f00\u59cb\u5faa\u73af\u62a2\u8bfe", None))
        self.saveAutoBtn.setText(QCoreApplication.translate("mainWindow", u"\u4fdd\u5b58\u8bfe\u7a0b\u5217\u8868", None))
        self.clearAutoBtn.setText(QCoreApplication.translate("mainWindow", u"\u6e05\u7a7a\u8bfe\u7a0b\u5217\u8868", None))
        self.loadAutoBtn.setText(QCoreApplication.translate("mainWindow", u"\u8bfb\u53d6\u8bfe\u7a0b\u5217\u8868", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autoSelector), QCoreApplication.translate("mainWindow", u"\u62a2\u8bfe\u4e2d\u5fc3", None))
        self.label_5.setText(QCoreApplication.translate("mainWindow", u"\u64cd\u4f5c\u65e5\u5fd7\uff1a", None))
        self.menu.setTitle(QCoreApplication.translate("mainWindow", u"\u8bbe\u7f6e", None))
        self.menu_2.setTitle(QCoreApplication.translate("mainWindow", u"\u5e2e\u52a9", None))
    # retranslateUi

