# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTableView, QWidget)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(1080, 976)
        mainWindow.setMinimumSize(QSize(1080, 760))
        mainWindow.setMaximumSize(QSize(1080, 976))
        self.preference = QAction(mainWindow)
        self.preference.setObjectName(u"preference")
        self.help = QAction(mainWindow)
        self.help.setObjectName(u"help")
        self.about = QAction(mainWindow)
        self.about.setObjectName(u"about")
        self.feedback = QAction(mainWindow)
        self.feedback.setObjectName(u"feedback")
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1081, 721))
        self.tabWidget.setMinimumSize(QSize(1081, 721))
        self.tabWidget.setMaximumSize(QSize(1081, 721))
        self.manualSelector = QWidget()
        self.manualSelector.setObjectName(u"manualSelector")
        self.typeComboBox = QComboBox(self.manualSelector)
        self.typeComboBox.setObjectName(u"typeComboBox")
        self.typeComboBox.setGeometry(QRect(340, 20, 141, 22))
        self.label = QLabel(self.manualSelector)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(270, 20, 71, 21))
        self.refresh = QPushButton(self.manualSelector)
        self.refresh.setObjectName(u"refresh")
        self.refresh.setGeometry(QRect(510, 20, 75, 24))
        self.searchEdit = QLineEdit(self.manualSelector)
        self.searchEdit.setObjectName(u"searchEdit")
        self.searchEdit.setGeometry(QRect(880, 20, 171, 21))
        self.label_3 = QLabel(self.manualSelector)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 50, 71, 21))
        self.label_4 = QLabel(self.manualSelector)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 430, 71, 21))
        self.chooseClass = QPushButton(self.manualSelector)
        self.chooseClass.setObjectName(u"chooseClass")
        self.chooseClass.setGeometry(QRect(460, 660, 75, 24))
        self.addAuto = QPushButton(self.manualSelector)
        self.addAuto.setObjectName(u"addAuto")
        self.addAuto.setGeometry(QRect(560, 660, 75, 24))
        self.epochComboBox = QComboBox(self.manualSelector)
        self.epochComboBox.setObjectName(u"epochComboBox")
        self.epochComboBox.setGeometry(QRect(100, 20, 141, 22))
        self.label_12 = QLabel(self.manualSelector)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 20, 71, 21))
        self.courseTable = QTableView(self.manualSelector)
        self.courseTable.setObjectName(u"courseTable")
        self.courseTable.setGeometry(QRect(30, 80, 1021, 341))
        self.courseTable.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.courseTable.setAlternatingRowColors(True)
        self.courseTable.setSelectionMode(QAbstractItemView.SingleSelection)
        self.courseTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.courseTable.setSortingEnabled(True)
        self.courseTable.setWordWrap(False)
        self.courseTable.horizontalHeader().setMinimumSectionSize(0)
        self.courseTable.horizontalHeader().setProperty(u"showSortIndicator", True)
        self.courseTable.horizontalHeader().setStretchLastSection(True)
        self.courseTable.verticalHeader().setMinimumSectionSize(0)
        self.courseTable.verticalHeader().setDefaultSectionSize(20)
        self.classTable = QTableView(self.manualSelector)
        self.classTable.setObjectName(u"classTable")
        self.classTable.setGeometry(QRect(30, 460, 1021, 191))
        self.classTable.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.classTable.setAlternatingRowColors(True)
        self.classTable.setSelectionMode(QAbstractItemView.SingleSelection)
        self.classTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.classTable.setWordWrap(False)
        self.classTable.horizontalHeader().setMinimumSectionSize(0)
        self.classTable.horizontalHeader().setStretchLastSection(True)
        self.classTable.verticalHeader().setVisible(True)
        self.classTable.verticalHeader().setMinimumSectionSize(0)
        self.classTable.verticalHeader().setDefaultSectionSize(20)
        self.tabWidget.addTab(self.manualSelector, "")
        self.autoSelector = QWidget()
        self.autoSelector.setObjectName(u"autoSelector")
        self.label_6 = QLabel(self.autoSelector)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 20, 111, 21))
        self.delAutoCourse = QPushButton(self.autoSelector)
        self.delAutoCourse.setObjectName(u"delAutoCourse")
        self.delAutoCourse.setGeometry(QRect(220, 460, 111, 24))
        self.autoCourseSwitch = QPushButton(self.autoSelector)
        self.autoCourseSwitch.setObjectName(u"autoCourseSwitch")
        self.autoCourseSwitch.setGeometry(QRect(350, 460, 111, 24))
        self.saveCourseList = QPushButton(self.autoSelector)
        self.saveCourseList.setObjectName(u"saveCourseList")
        self.saveCourseList.setGeometry(QRect(480, 460, 111, 24))
        self.clearCourseList = QPushButton(self.autoSelector)
        self.clearCourseList.setObjectName(u"clearCourseList")
        self.clearCourseList.setGeometry(QRect(610, 460, 111, 24))
        self.loadCourseList = QPushButton(self.autoSelector)
        self.loadCourseList.setObjectName(u"loadCourseList")
        self.loadCourseList.setGeometry(QRect(740, 460, 111, 24))
        self.autoCourseTable = QTableView(self.autoSelector)
        self.autoCourseTable.setObjectName(u"autoCourseTable")
        self.autoCourseTable.setGeometry(QRect(30, 50, 1021, 391))
        self.autoCourseTable.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.autoCourseTable.setAlternatingRowColors(True)
        self.autoCourseTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.autoCourseTable.setWordWrap(False)
        self.autoCourseTable.horizontalHeader().setMinimumSectionSize(0)
        self.autoCourseTable.horizontalHeader().setStretchLastSection(True)
        self.autoCourseTable.verticalHeader().setVisible(True)
        self.autoCourseTable.verticalHeader().setMinimumSectionSize(0)
        self.autoCourseTable.verticalHeader().setDefaultSectionSize(20)
        self.tabWidget.addTab(self.autoSelector, "")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 730, 71, 21))
        self.cmdOutput = QPlainTextEdit(self.centralwidget)
        self.cmdOutput.setObjectName(u"cmdOutput")
        self.cmdOutput.setGeometry(QRect(30, 760, 1021, 151))
        self.cmdOutput.setReadOnly(True)
        self.cmdOutput.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1080, 23))
        font = QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tabWidget, self.typeComboBox)
        QWidget.setTabOrder(self.typeComboBox, self.refresh)
        QWidget.setTabOrder(self.refresh, self.cmdOutput)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.preference)
        self.menu_2.addAction(self.help)
        self.menu_2.addAction(self.about)
        self.menu_2.addAction(self.feedback)

        self.retranslateUi(mainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"\u9009\u8bfe\u52a9\u624b", None))
        self.preference.setText(QCoreApplication.translate("mainWindow", u"\u9996\u9009\u9879", None))
        self.help.setText(QCoreApplication.translate("mainWindow", u"\u4f7f\u7528\u5e2e\u52a9", None))
        self.about.setText(QCoreApplication.translate("mainWindow", u"\u5173\u4e8e\u8f6f\u4ef6", None))
        self.feedback.setText(QCoreApplication.translate("mainWindow", u"\u95ee\u9898\u53cd\u9988", None))
        self.label.setText(QCoreApplication.translate("mainWindow", u"\u8bfe\u7a0b\u7c7b\u578b\uff1a", None))
        self.refresh.setText(QCoreApplication.translate("mainWindow", u"\u5237\u65b0", None))
        self.searchEdit.setPlaceholderText(QCoreApplication.translate("mainWindow", u"\u952e\u5165\u4ee5\u641c\u7d22", None))
        self.label_3.setText(QCoreApplication.translate("mainWindow", u"\u8bfe\u7a0b\u5217\u8868\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("mainWindow", u"\u53ef\u9009\u8bb2\u53f0\uff1a", None))
        self.chooseClass.setText(QCoreApplication.translate("mainWindow", u"\u9009\u62e9\u8bb2\u53f0", None))
        self.addAuto.setText(QCoreApplication.translate("mainWindow", u"\u52a0\u5165\u62a2\u8bfe", None))
        self.label_12.setText(QCoreApplication.translate("mainWindow", u"\u9009\u8bfe\u8f6e\u6b21\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manualSelector), QCoreApplication.translate("mainWindow", u"\u9009\u8bfe\u4e2d\u5fc3", None))
        self.label_6.setText(QCoreApplication.translate("mainWindow", u"\u5faa\u73af\u62a2\u8bfe\u8bfe\u7a0b\u5217\u8868\uff1a", None))
        self.delAutoCourse.setText(QCoreApplication.translate("mainWindow", u"\u5220\u9664\u9009\u4e2d\u7684\u8bfe\u7a0b", None))
        self.autoCourseSwitch.setText(QCoreApplication.translate("mainWindow", u"\u5f00\u59cb\u5faa\u73af\u62a2\u8bfe", None))
        self.saveCourseList.setText(QCoreApplication.translate("mainWindow", u"\u4fdd\u5b58\u8bfe\u7a0b\u5217\u8868", None))
        self.clearCourseList.setText(QCoreApplication.translate("mainWindow", u"\u6e05\u7a7a\u8bfe\u7a0b\u5217\u8868", None))
        self.loadCourseList.setText(QCoreApplication.translate("mainWindow", u"\u8bfb\u53d6\u8bfe\u7a0b\u5217\u8868", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autoSelector), QCoreApplication.translate("mainWindow", u"\u62a2\u8bfe\u4e2d\u5fc3", None))
        self.label_5.setText(QCoreApplication.translate("mainWindow", u"\u64cd\u4f5c\u65e5\u5fd7\uff1a", None))
        self.menu.setTitle(QCoreApplication.translate("mainWindow", u"\u8bbe\u7f6e", None))
        self.menu_2.setTitle(QCoreApplication.translate("mainWindow", u"\u5e2e\u52a9", None))
    # retranslateUi

